# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Pre-commit hooks configuration for ultralytics-actions
# This file allows other repositories to use ultralytics-actions in their pre-commit config

- id: update-file-headers
  name: Update File Headers
  description: Add or update file headers with license information
  entry: ultralytics-actions headers
  language: python
  types_or: [python, yaml, shell, c, c++, java, javascript, typescript, swift, dart, rust]
  pass_filenames: false
  require_serial: true

- id: format-python-docstrings
  name: Format Python Docstrings
  description: Format Python docstrings to Google style
  entry: ultralytics-actions format-python-docstrings
  language: python
  types: [python]
  pass_filenames: false
  require_serial: true

- id: update-markdown-code-blocks
  name: Update Markdown Code Blocks
  description: Format code blocks in Markdown files
  entry: ultralytics-actions update-markdown-code-blocks
  language: python
  types: [markdown]
  pass_filenames: false
  require_serial: true
