# Ultralytics Actions 🚀, AGPL-3.0 License https://ultralytics.com/license

name: "Disk Space Cleanup"
author: "Ultralytics"
description: "Cleans up disk space by removing unnecessary tool caches and packages"
runs:
  using: "composite"
  steps:
    - name: Cleanup disk space
      shell: bash
      run: |
        echo "Free space before deletion:"
        df -h /
        # Remove tool cache to free up ~15GB of space per https://github.com/ultralytics/ultralytics/pull/15848
        rm -rf /opt/hostedtoolcache || true
        echo "Free space after deletion:"
        df -h /
